version: '3.8'

services:
  xml-to-dsl:
    build: .
    container_name: xml-to-dsl-app
    ports:
      - "9000:9000"
    volumes:
      - ./uploads:/app/uploads
      - ./frontend/templates:/app/frontend/templates  # Mount templates
    restart: always

